#App
app:
  sub-domain: sub1
  bounded-context: bd1
  microservice: user
  swagger-url: /swagger-ui.html#/

#Server
server:
  servlet:
    context-path: /netflix/api/v1

#JPA
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none

#Logging
logging:
  level:
    org.springframework: error
  pattern:
    file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"