#Datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/netflix-user-db
    username: postgres
    password: 12345

#Server
server:
  port: ${app.port:11000}

#Logging
logging:
  file:
    name: src/main/resources/logs/netflix-ms-user-${app.port:11000}.log